/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import java.util.List;
import javax.swing.JOptionPane;
import model.Profesor;
import model.Status;

/**
 *
 * @author Acer
 */
public class Zadatak2 extends javax.swing.JFrame {

    /**
     * Creates new form Zadatak2
     */
    private List<Profesor> profesori;
    Controller kontroler;
    public Zadatak2() {
        initComponents();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfesori = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProfesori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProfesori);

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        int selektovaniRed = tblProfesori.getSelectedRow();
        List<Profesor> prof = Controller.getInstance().ucitajListuIzBaze();
        Profesor p = prof.get(selektovaniRed);
        Status st = p.getStatus();
        //if(st.equals(Status.AKTIVAN))
        if(selektovaniRed == -1 && !st.equals(Status.AKTIVAN)){
            JOptionPane.showMessageDialog(this,"Nije selektovan red.","Greska", JOptionPane.INFORMATION_MESSAGE); 
            return;
        }
        else{
            Profesor profZaIzmenu = Controller.getInstance().ucitajListuIzBaze().get(selektovaniRed);
            IzmeniProfesora ip = new IzmeniProfesora(this,true,profZaIzmenu);
            ip.setVisible(true);
            
        }
        
        
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProfesori;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        List<Profesor> sviProfesori = Controller.getInstance().ucitajListuIzBaze();
        ModelTabeleProfesor mtp = new ModelTabeleProfesor(sviProfesori);
        tblProfesori.setModel(mtp);
    }

    void azurirajTabelu() {
        List<Profesor> lista = Controller.getInstance().ucitajListuIzBaze();
        ModelTabeleProfesor mtp = new ModelTabeleProfesor(lista);
        tblProfesori.setModel(mtp);
        
    }
}
